/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author 10jon
 */
public class ClockGUI extends javax.swing.JFrame {

    /**
     * Creates new form ClockGUI
     */
    private List<ClockPanel> panels;
    private List<Thread> threads;
    private int numOfClocks = 0;
    private int counter = 0;
    
    public ClockGUI() {
        initComponents();
        setSize(1000, 500);
        panels = new ArrayList<>();
        threads = new ArrayList<>();
        MainPanel.setBackground(Color.white);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btNew = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btNew.setText("Add new Clock");
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onNewClock(evt);
            }
        });
        getContentPane().add(btNew, java.awt.BorderLayout.PAGE_END);

        MainPanel.setLayout(new java.awt.GridLayout(3, 1, 0, 20));
        getContentPane().add(MainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onNewClock(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onNewClock
        if(numOfClocks<3){
            int timezone = -12;
            while(timezone < -11 || timezone > 14){
                try{
                    timezone = Integer.parseInt(JOptionPane.showInputDialog("Please enter time zone (-11 to +14): "));
                    if(timezone < -11 || timezone > 14){
                        JOptionPane.showMessageDialog(this, "Time Zone invalid!");
                    }
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(this, "Please enter a valid integer number!");
                }
                
            }
            
            ClockPanel panel = new ClockPanel(counter, this, timezone);
            panels.add(panel);
            this.MainPanel.add(panel);
            Thread thread = new Thread((Runnable)panel);
            thread.start();
            threads.add(thread);
            this.setSize(1001, 500);
            this.setSize(1000, 500);
            numOfClocks++;
            counter++;
        }
    }//GEN-LAST:event_onNewClock

    public void stopClock(int id){
        threads.get(id).interrupt();
        MainPanel.remove(panels.get(id));
        MainPanel.revalidate();
        this.setSize(1001, 500);
        this.setSize(1000, 500);
        //panels.remove(id);
        //threads.remove(id);
        numOfClocks--;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClockGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClockGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btNew;
    // End of variables declaration//GEN-END:variables
}
