/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BL.Account;
import BL.User;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author 10jon
 */
public class AccountGUI extends javax.swing.JFrame {

    /**
     * Creates new form AccountGUI
     */
    public DefaultListModel users;
    public Account account;
    private boolean runningTests = false;

    public AccountGUI() {
        initComponents();
        this.setSize(600, 450);
        this.setLocationRelativeTo(null);
        users = new DefaultListModel();
        liList.setModel(users);
        account = new Account(50, lbBalance);
        account.setBalance(50);
        DefaultCaret caret = (DefaultCaret)taOut.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        //Test Users
        for (int i = 0; i < 10000; i++) {
            users.addElement(new User(account, 1000, "u"+i, taOut));
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUp = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        liList = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        lbBalance = new javax.swing.JLabel();
        btReset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        taOut = new javax.swing.JTextArea();

        jMenuItem1.setText("Add User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onNewUser(evt);
            }
        });
        popUp.add(jMenuItem1);

        jMenuItem2.setText("Perform Account Test");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPerformTest(evt);
            }
        });
        popUp.add(jMenuItem2);

        jMenuItem3.setText("Delete User(s)");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDeleteUser(evt);
            }
        });
        popUp.add(jMenuItem3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Users"));
        jScrollPane1.setHorizontalScrollBar(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 450));

        liList.setComponentPopupMenu(popUp);
        jScrollPane1.setViewportView(liList);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.LINE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Balance", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lbBalance.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(lbBalance, java.awt.BorderLayout.LINE_END);

        btReset.setText("Reset Account");
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onReset(evt);
            }
        });
        jPanel1.add(btReset, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log-output", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jScrollPane2.setHorizontalScrollBar(null);

        taOut.setEditable(false);
        taOut.setColumns(20);
        taOut.setRows(5);
        jScrollPane2.setViewportView(taOut);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onNewUser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onNewUser
        String name = JOptionPane.showInputDialog("Enter name: ");
        User user = new User(account, 10, name, taOut);
        List<String> usersString = new ArrayList<>();
        for (int i = 0; i < users.size(); i++) {
            usersString.add(users.get(i) + "");
        }
        if (!usersString.contains(user + "")) {
            users.addElement(user);
        } else {
            JOptionPane.showMessageDialog(this, "Every name has to be unique!");
        }

    }//GEN-LAST:event_onNewUser

    private void onPerformTest(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPerformTest
        List<User> list = liList.getSelectedValuesList();
        for (int i = 0; i < list.size(); i++) {
            User user = (User) list.get(i);
            Thread thread = new Thread((Runnable) user);
            thread.setPriority(thread.getPriority() + 1);
            thread.start();
        }
    }//GEN-LAST:event_onPerformTest

    private void onReset(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onReset
        account.setBalance(50);
        taOut.setText("");
    }//GEN-LAST:event_onReset

    private void onDeleteUser(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDeleteUser
        List<User> toDelete = liList.getSelectedValuesList();
        for (User user : toDelete) {
            users.removeElement(user);
        }
    }//GEN-LAST:event_onDeleteUser

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReset;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBalance;
    private javax.swing.JList<User> liList;
    private javax.swing.JPopupMenu popUp;
    private javax.swing.JTextArea taOut;
    // End of variables declaration//GEN-END:variables
}
