/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import bl.BruteforceManager;
import java.awt.JobAttributes;
import javax.swing.JOptionPane;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author 10jon
 */
public class BruteforceGUI extends javax.swing.JFrame {

    /**
     * Creates new form BruteforceGUI
     */
    public BruteforceGUI() {
        initComponents();
        this.setSize(500, 500);
        this.setLocationRelativeTo(null);
        DefaultCaret caret = (DefaultCaret) taLog.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
    }
    
    public static boolean running = false;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tfPass = new javax.swing.JTextField();
        slThreads = new javax.swing.JSlider();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();
        btStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bruteforce");
        jPanel2.add(jLabel1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Passwörter"));
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(tfPass, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel1);

        slThreads.setMajorTickSpacing(4);
        slThreads.setMaximum(32);
        slThreads.setMinorTickSpacing(1);
        slThreads.setPaintLabels(true);
        slThreads.setPaintTicks(true);
        slThreads.setSnapToTicks(true);
        slThreads.setBorder(javax.swing.BorderFactory.createTitledBorder("Threads"));
        jPanel2.add(slThreads);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));

        taLog.setEditable(false);
        taLog.setColumns(20);
        taLog.setRows(5);
        jScrollPane1.setViewportView(taLog);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        btStart.setText("Start");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onStart(evt);
            }
        });
        jPanel3.add(btStart, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onStart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onStart
        if (!running) {
            taLog.setText("");
            running = true;
            int numPasswords = 0;
            try {
                numPasswords = Integer.parseInt(tfPass.getText());
            } catch (NumberFormatException e) {
                while ((numPasswords == -1) || (numPasswords > 100) || (numPasswords < 1)) {
                    try {
                        numPasswords = Integer.parseInt(JOptionPane.showInputDialog("Please enter a valid number!"));
                    } catch (NumberFormatException ex) {
                        numPasswords = -1;
                    }
                }
            }
            int numThreads = slThreads.getValue();
            BruteforceManager br = new BruteforceManager(taLog, numPasswords, numThreads);
            Thread t = new Thread((Runnable) br);
            t.start();
        }
        else{
            JOptionPane.showMessageDialog(this, "Another Crack is already running!");
        }

    }//GEN-LAST:event_onStart

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BruteforceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BruteforceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BruteforceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BruteforceGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BruteforceGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider slThreads;
    private javax.swing.JTextArea taLog;
    private javax.swing.JTextField tfPass;
    // End of variables declaration//GEN-END:variables
}
